name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required to publish a release

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ext: ""
          - os: windows-latest
            ext: ".exe"
          - os: macos-latest
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev

      - name: Build binary
        run: cargo build --release

      - name: Rename output binary
        run: mv target/release/bnetchat${{ matrix.ext }} target/release/bnetchat-${{ matrix.os }}${{ matrix.ext }}
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/bnetchat-${{ matrix.os }}${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
