name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install system dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev

      - name: Build binary
        run: cargo build --release

      - name: Rename output (platform specific)
        run: |
          ext=""
          if [[ "${{ runner.os }}" == "Windows" ]]; then ext=".exe"; fi
          mv target/release/bnetchat target/release/bnetchat-${{ runner.os }}$ext

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/bnetchat-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
